from django.urls import path
from django.contrib import admin
from . import views
from django.views.generic.base import RedirectView
urlpatterns = [
    path('', views.identify, name='identify'),


    path('login/', views.login_page, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/',views.registerUser,name='register'),
    path('profile-fillup/',views.profile_fillUp,name='profile-fillup'),
    path('schedule-fillup/',views.schdeule_fillup, name="sched-fill"),
    path('schedule/',views.schedule, name="schedule"),
    path('reservation',views.reservation,name='reservation'),
    path('reservation-driver-info/<str:pk>/',views.reservation_driver_info,name='driver-info-reservation'),
    path('reservation-cancelation/<str:pk>/',views.cancel_reservation, name="cancel-reservation"),


    path('waiting-cancelation/',views.waiting_cancelation,name="wait-cancel"),
    path('reserved_not_confirmed/', views.existing_reservation, name='cancel-reserve'),
    path('driver-reservation-decline/<str:pk>/',views.driver_reservation_declined,name="drvr-decline-rsrv"),
    path('driver-reservation-accept/<str:pk>/',views.driver_reservation_accpeted,name="drvr-accept-rsrv"),
    path('driver-reservations', views.driver_reservations, name="driver-reservations"),
    path('driver-reservations-info/<str:pk>/',views.driver_reservation_info, name="driver-reserve-info"),
    path('driver-register/', views.driver_register_page, name='driver-register'),
    path('driver-mainNavbPage/',views.drivermainNavPage,name='DrivernavPage'),
    path('driver-profile-fillup/',views.driver_profile_fillUp,name='driver-profile-fillup'),
    path('driver-profile/<str:pk>/', views.driver_profile_page, name='driver-profile'),
    path('driver-security-settings/<str:pk>/', views.driver_security_settings, name='driver-security'),
    path('driver-edit-profile/<str:pk>/', views.edit_driver_profile, name='driver-edit-profile'),
    path('dirver_myservice/',views.driver_myservice, name='myservice-driver'),
    path('driver-add-pickup-time/<str:pk>/',views.driver_add_pickup_time,name="add-pickup"),
    path('change_password', views.password_change, name='change-password'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
    path('registration-identify',views.registration_choices,name="registration-choose"),

    
    path('driver-feedback/<str:pk>/',views.student_driver_feedback,name="driver-feedback"),
    path('student-payments/<str:pk>/',views.student_payments, name="stdnt-payment"),
    path('mainNavbPage/',views.mainNavPage,name='navPage'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('edit-profile/<str:pk>/', views.editProfile, name='edit-profile'),
    path('main-reservation-page/<str:pk>/', views.pay_reservation, name='pay-reservation'),
    path('payment/<str:pk>/',views.payment,name="payment"),
    path('student-my-service/',views.student_myservice,name='myservice'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('not-allowed/', views.not_allowed, name='not-allowed'),
     path('announcement/', views.announcements, name='announcement'),
     
    path('admin-nav/', views.admin_nav_page, name="admin-nav"),
    path('admin-students/', views.admin_students,name="admin-students"),
    path('admin-student/delete/<str:pk>/' ,views.admin_student_delete,name="stdnt-dlt"),
    path('admin-indiv-students/<str:pk>/', views.admin_students_indiv, name="admin-stdnt-info"),
    path('admin-stdnt-edit/<str:pk>/', views.admin_student_edit, name="admin-stdnt-edit"),
    path('admin-drivers/', views.admin_drivers,name="admin-drivers"),
    path('admin-add-driver/',views.admin_add_driver,name="add-driver"),
    path('admin-indiv-drivers/<str:pk>/', views.admin_drivers_indiv, name="admin-drvr-info"),
    path('admin-drvr-edit/<str:pk>/',views.admin_driver_edit,name="admin-drvr-edit"),
    path('admin-reservations/', views.admin_reservations,name="admin-reservations"),
    path('admin-add-reservation/',views.admin_add_reservation,name='add-reservation'),
    path('admin-indiv-reservations/<str:pk>/', views.admin_reservation_indiv, name="admin-rsrv-info"),
    path('admin-reservations-edit/<str:pk>/', views.admin_reservation_edit, name="admin-rsrvtns-edit"),
    path('admin-reservations-decline/<str:pk>/', views.admin_reservation_decline, name="admin-rsrvtns-decline"),
     path('admin-indiv-cancelations/<str:pk>/', views.admin_cancelation_individual, name="admin-cancelations-info"),
    path('admin-reservation-cancelations',views.admin_reservation_cancelations,name="reservation-cancelation"),
    path('admin-cancelation-accept/<str:pk>/', views.admin_cancelation_accept,name="accept-cancel"),
    path('admin-cancelation-decline/<str:pk>/',views.admin_cancelation_decline,name="admin-cancelation-decline"),
    path('admin-vehicles/',views.admin_vehicles,name='vehicles'),
    path('admin-vehicle-create/',views.admin_vehicle_add,name="admin-add-vehicle"),
    path('admin-vehicle-request/',views.admin_vehicle_request,name="admin-vehicle-req"),
    path('admin-vehicle-req-indiv/<str:pk>/',views.admin_vehicle_request_indiv,name="vehicle-indiv-req"),
    path('admin--payment/',views.admin_payment_request, name= "admin-payments"),
    path('admin-payment-indiv/<str:pk>/', views.admin_payments_indiv, name="admin-payment-indiv"),
    path('admin-payments-decline/<str:pk>/',views.admin_payments_decline,name="payments-decline"),
    path('admin-vehicle-decline/<str:pk>/', views.admin_vehicle_request_decline,name="decline-vehicle-req"),
    path('admin-vehicles-individual/<str:pk>/',views.admin_vehicles_individual,name='vehicles-individual'),
    path('admin-vehicle/delete/<str:pk>/' ,views.admin_vehicle_delete,name="vhcl-dlt"),
    path('admin-vhcl-edit/<str:pk>/',views.admin_vehicle_edit,name="vhcl-edit"),
    path('admin-vehicles-updates-indiv/<str:pk>/',views.admin_vehicle_updates_indiv,name='admin-vehicles-update-indiv'),
    path('admin-announcements/',views.admin_announcements,name="admin-anncmnts"),
    path('admin-add-announcements/',views.admin_add_announcements,name="add-anncmnts"),
    path('admin-announcements-individual/<str:pk>/',views.admin_announcements_individual,name="admin-anncmnts-indiv"),
    path('admin-announcements-edit/<str:pk>/',views.admin_announcements_edit,name="admin-anncmnts-edit"),
    path('admin-announcements-delete/<str:pk>/',views.admin_announcements_delete,name="admin-anncmnts-delete"),
    path('admin-create-student/',views.admin_create_student,name="add-student"),
    path('admin-franchises',views.admin_franchise, name="admin-franchise"),
    path('admin-franchise-add/',views.admin_register_franchise,name='add-franchise-admin'),
    path('admin-indiv-franchises/<str:pk>/',views.admin_franchise_indiv, name="admin-indiv-franchise"),
    path('franchise_decline/<str:pk>/',views.admin_franchise_decline,name="franchise-decline"),
    path('admin-franchise-add/',views.admin_franchise_add, name="add_franchise"),
    path('admin-franchise-drive-reqs-indiv/<str:pk>/', views.admin_franchise_driver_reqs_indiv,name="driver-reqs-indiv"),
    path('admin-franchise-users/',views.admin_franchise_users,name="add-franchise-users"),
    path('admin-franchise-delete/<str:pk>/',views.admin_franchise_delete,name="admin-dlt-franchise"),
    path('admin_indiv-franchise_user/<str:pk>/',views.admin_franchiser_users_indiv,name="indiv-franchise-users"),
    path('admin-franchise-users-indiv-edit/<str:pk>/',views.admin_franchise_users_edit, name="admin-franchise-users-indiv-edit"),
    path('admin-franchise-drivers-requests/',views.admin_franchise_driver_reqs,name="driver-requests-admin"),
    path('admin-driver-membership-payment/', views.admin_driver_membership_payments, name= "admin-membership"),
    path('admin-driver-membership-indiv/<str:pk>/',views.admin_driver_membership_payments_indiv, name="admin-mebership-indiv"),
    path('admin-requests-services/',views.admin_services_requests, name="admin-requests-services"),
    path('admin-services-indiv/<str:pk>/',views.admin_services_requests_indiv, name="admin-indiv-services"),
    path('admin-services-decline/<str:pk>/',views.admin_services_decline, name="admin-services-decline"),
    path('admin-add-services/',views.admin_add_services, name="admin-add-service"),
    path('admin-feedbacks/',views.admin_feedbacks,name='admin-feedbacks'),
    path('admin-feedback-indiv/<str:pk>/',views.admin_feedback_indiv,name="feedback-indiv"),
    path('admin-notify-admin/<str:pk>/',views.admin_notify_feedback, name='admin-notify'),
    path('admin-reports', views.admin_reports, name='admin-reports'),
    path('pdf_reports/',views.render_pdf_view,name='print-pdf-resmonth'),
    path('pdf_report_res_daily/',views.pdf_report_res_daily, name="res-daily"),
    path('pdf_all_reservation/',views.render_pdf_all,name="pdf-all-res"),
    path('pdf_reports_yearly',views.render_pdf_view_yearly, name="pdf-yearly"),
    path('pdf-report-all-payments/',views.render_pdf_payment_all,name='pdf-payments-all-rprt'),
    path('pdf-report-monthly-payments/',views.render_pdf_payment_month,name="monthly-payments"),
    path('pdf-payments-yearly/',views.render_pdf_payment_yearly, name="yearly-payments-report"),
    path('pdf-daily-payments/',views.pdf_reports_payment_daily, name="daily-payments"),
    path('pdf-users-all/',views.render_pdf_user_all, name="pdf-users-all"),
    path('pdf-sum/',views.all_report, name="all"),
    path('admin-reservation-cancelations', views.admin_reservation_deactivate,name="cancel-service-reservation"),
    path('admin-membership-decline/<str:pk>/',views.admin_membership_payment_decline, name='admin-membership-decline'),
    #path('admin-franchise-delete/<str:pk>/',views.admin_franchise_delete, name="delete_franchise"),
    
    path('otc-payments/<str:pk>/', views.otc_payments,name="otc_payments"),
    path('bayad_center/<str:pk>/', views.bayad_center, name="bayad_center"),
    path('imc-tellering-payment/<str:pk>/',views.imc_tellering,name="imc-tellering"),
    path('payment-summary/<str:pk>/', views.payment_summary, name="payment-summary"),
    path('franchise-registration/',views.franchise_registration, name="franchise-register"),
    path('submit-proof-of-payment/<str:pk>/',views.submit_proof_of_payment, name="proof-payment"),
    
    
    path('no-driver/',views.no_drivers,name="no-driver"),
    path('franchise_nav/',views.franchise_nav,name='franchise-nav'),
    path('franchise-drivers/',views.frannchise_drivers,name="franchise-drivers"),
    path('franchise-drivers-indiv/<str:pk>/',views.franchise_drivers_indiv,name="indiv-franchise-drivers"),
    path('franchise-drivers-add',views.franchise_regiter_driver,name="franchise-register-drivers"),
    path('franchise-vehicles', views.franchise_vehicles, name="franchise-vehicles"),
    path('franchise-individual-vehicles/<str:pk>/',views.franchise_vehicles_individual, name="franchise-vehicles-indiv"),
    path('franchise-vehilce-retire/<str:pk>/',views.franchise_vehicles_retire, name="retire-vehicle"),
    path('franchise-individual-vehicles-edit/<str:pk>/',views.franchise_vehicles_individual_edit, name="franchise-vehicles-indiv-edit"),
    path('franchise-register-vehicle/',views.franchise_regisater_vehicle,name="franchise-register-vehicle"),
    path('franchise-services',views.franchise_services, name="franchise-services"),
    path('franchise-services-individual/<str:pk>/',views.franchise_services_indiv, name="franchise-services-indiv"),
    path('franchise-services-edit/<str:pk>/',views.franchise_service_edit, name="franchise_service_edit"),
    path('franchise-services-regiister/', views.franchise_services_register, name="franchise-services-reg"),
    path('franchise-membership-fee-driver/',views.franchise_driver_membership_pay,name="membership"),
    path('franchise-membership-indiv-payment/<str:pk>/', views.franchise_driver_membership_pay_indiv, name="membership-indiv"),
    path('franchise-services-register/<str:pk>/',views.franchise_profile, name="franchise-profile"),
    path('franchise-pdf-generator/<str:pk>/', views.membership_payment_pdf, name='membership_pay_pdf'),
    path('franchise-membership-proof-of-payment/',views.franchise_membership_proof, name="membership-proof"),
    #path('admin_franchise_drivers/<str:pk>/',views.franchise_driver_proof_of_payment, name="driver-pop"),
    path('generate-pdf/<str:pk>/',views.pdf_generator,name='pdf_gen' ),
    path('faq/',views.faq,name='faq'),
    path('privacypolicies/',views.privacypolicy, name="privacy"),
    path('terms/',views.termsncond,name="terms")

    
]
