# Generated by Django 4.2 on 2023-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='franchisedrivers',
            name='payment_status',
            field=models.CharField(choices=[('SUCCESSFULL', 'Successfull'), ('FAILED', 'Failed'), ('PENDING', 'pending'), ('null', ' ')], default='PENDING', max_length=100),
        ),
    ]
