# Generated by Django 4.2 on 2023-04-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid')], default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESSFULL', 'successfull'), ('DECLINED', 'declined')], default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='included',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentReservationCancelation',
            fields=[
                ('cancelation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(max_length=500)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reservation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
