# Generated by Django 4.2 on 2023-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('RESERVATION', 'Reservation'), ('MEMBERSHIP', 'Membership'), ('null', '')], default='null', max_length=20),
        ),
    ]
