# Generated by Django 4.2 on 2023-05-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purpose',
        ),
    ]
