# Generated by Django 4.2 on 2023-04-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_studentreservationcancelation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentReservationCancelation',
            new_name='ReservationCancelation',
        ),
    ]
