# Generated by Django 4.2 on 2023-05-16 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_payment_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('ref_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('SUCCESSFULL', 'Successfull'), ('FAILED', 'Failed'), ('PENDING', 'pending'), ('null', ' ')], default='null', max_length=20)),
                ('total', models.FloatField(null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
