# Generated by Django 4.2 on 2023-05-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_driverpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpayment',
            name='user',
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.franchisedrivers'),
        ),
    ]
