# Generated by Django 4.2 on 2023-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reservationcancelation_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='for_cancelation',
            field=models.BooleanField(default=False),
        ),
    ]
