# Generated by Django 4.2 on 2023-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reservation_for_cancelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='for_cancelation',
        ),
    ]
