# Generated by Django 4.2 on 2023-05-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_driverpayment_franchise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='retirement_reason',
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='status',
            field=models.CharField(choices=[('SUCCESSFULL', 'Successfull'), ('FAILED', 'Failed'), ('PENDING', 'pending'), ('null', ' ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehiclerequest'),
        ),
    ]
