# Generated by Django 4.2 on 2023-04-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_reservation_for_cancelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESSFULL', 'successfull'), ('DECLINED', 'declined'), ('FORCANCELATION', 'for cancelation')], default='PENDING', max_length=100),
        ),
    ]
