# Generated by Django 4.2 on 2023-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vehicle_image_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcancelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationcancelation',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING', 'pending')], default='PENDING', max_length=100),
        ),
    ]
