# Generated by Django 4.2 on 2023-05-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_accounts_balance_alter_driverpayment_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESSFULL', 'Successfull'), ('FAILED', 'Failed'), ('PENDING', 'pending'), ('null', ' ')], default='PENDING', max_length=20),
        ),
    ]
