# Generated by Django 4.2 on 2023-04-29 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_announcement_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='franchise_no',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='operator',
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('franchise_name', models.CharField(max_length=100)),
                ('franchise_no', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driverprofile')),
            ],
        ),
    ]
