# Generated by Django 4.2 on 2023-04-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_driverprofile_franchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='driver',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.franchise'),
        ),
    ]
