# Generated by Django 4.2 on 2023-05-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_accounts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reservation'),
        ),
    ]
