# Generated by Django 4.2 on 2023-04-30 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_franchise_driver_driverprofile_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.driverprofile')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
    ]
