# Generated by Django 4.2 on 2023-04-30 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_services_reservation_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='driver',
        ),
        migrations.AddField(
            model_name='services',
            name='franchise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.franchise'),
        ),
    ]
