# Generated by Django 4.2 on 2023-04-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_services_driver_services_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pick_up',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
